FRAUD = ["Your PayPal account has been temporarily suspended. Please click the link to confirm your identity.",
"Win a free Xbox Series X! Enter your details to be entered.",
"Urgent notification: Your credit card has been used for a suspicious transaction. Call our hotline immediately.",
"Get a 100 euro voucher by participating in our survey. Enter your account details to receive the voucher.",
"Your account has been compromised. Click here to change your password and protect your account.",
"Win an iPhone 13 Pro! Enter your personal information to be entered into the sweepstakes.",
"Your Netflix membership has been suspended. Please update your payment information to continue service.",
"Congratulations, you have won 1 million euros in the lottery! To receive your winnings, please provide us with your bank account information.",
"Update your bank account to continue benefiting from the latest security features. Enter your details to continue.",
"Warning: your Amazon account has been hacked. Confirm your identity to restore it.",
"You have been selected as a winner! Pay a processing fee to collect your prize.",
"Your email account will be deleted in 24 hours if you don't verify your credentials.",
"Your email account will be deleted in 24 hours if you do not verify your credentials.",
"Free sample of our exclusive product! Enter your shipping address and credit card information.",
"Your bank account has been temporarily suspended. Click on the link to fix the problem.",
"Win a luxury trip to Hawaii! Enter your information to be entered into the sweepstakes.",
"Your payment for order #12345 has been declined. Please update your payment information.",
"Urgent notification: Your Microsoft account has been hacked. Click here to reset your password.",
"You have won a 500 euro voucher! Let us know your bank details to receive it.",
"Your membership is about to expire. Enter your credit card details to renew."]

TRUSTWORTHY = ["The weather today will be sunny and warm with a maximum temperature of 25 degrees Celsius.",
"The new film by the renowned director will premiere in theaters tomorrow.",
"Please note that our office will be closed next Monday.",
"We are pleased to inform you that you have won the first place in the painting contest.",
"Our company supports several non-profit organizations through donations and volunteerism.",
"The book fair will be held online this year, so everyone can participate.",
"The restaurant offers a variety of delicious dishes from around the world in a cozy atmosphere.",
"Please note that the 11:15 a.m. train will be delayed 10 minutes.",
"Our customer service team is always available to answer your questions.",
"The city government is organizing a music festival in the city park next weekend.",
"We would like to thank all of our customers for their years of support.",
"The new school year begins September 2. Please make sure your child starts school on time.",
"We are pleased to announce that our product has won the Innovation Award.",
"The author will give a reading from his latest book and answer questions afterwards.",
"The concert by the famous band is already sold out, but tickets are still available for the additional show.",
"Please remember to renew your membership to take advantage of all the benefits.",
"The art show will feature a wide range of stunning paintings and sculptures."]